# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 11:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(help_text='Nombre del país', max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='pais',
            unique_together=set([('nombre',)]),
        ),
    ]
