# Generated by Django 2.0.4 on 2018-04-27 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacomercialcuenta',
            name='cci',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Ingrese un número de cci válido.')], verbose_name='Número de cci'),
        ),
        migrations.AlterField(
            model_name='marcacomercialcuenta',
            name='cta',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Ingrese un número de cuenta válido.')], verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='marcacomercialcuenta',
            name='titular',
            field=models.CharField(help_text='Nombre del titular de la cuenta', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válida.')], verbose_name='Titular'),
        ),
    ]
