# Generated by Django 2.0.3 on 2018-03-27 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.CharField(help_text='Siglas de la ciudad', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3}$', message='Ingrese siglas válidas.')], verbose_name='Ciudad')),
                ('nombre', models.CharField(help_text='Nombre de la ciudad', max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre')),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pais')),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'verbose_name': 'ciudad',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('pais', 'nombre')},
        ),
    ]
