# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
