# Generated by Django 2.0.3 on 2018-03-27 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180327_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nombre',), 'verbose_name': 'país', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.CharField(help_text='Siglas de la ciudad', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3}$', message='Ingrese siglas válidas.')], verbose_name='Siglas'),
        ),
    ]
