# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171120_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
