# Generated by Django 2.0.5 on 2018-05-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180510_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'ordering': ('nombre',), 'verbose_name': 'banco', 'verbose_name_plural': 'bancos'},
        ),
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ('nombre',), 'verbose_name': 'categoría de servicio', 'verbose_name_plural': 'categorías de servicio'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ('nombre',), 'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ('nombre',), 'verbose_name': 'idioma', 'verbose_name_plural': 'idiomas'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ('nombre',), 'verbose_name': 'localidad', 'verbose_name_plural': 'localidades'},
        ),
        migrations.AlterModelOptions(
            name='marcacomercial',
            options={'ordering': ('nombre',), 'verbose_name': 'marca comecial', 'verbose_name_plural': 'marcas comerciales'},
        ),
        migrations.AlterModelOptions(
            name='modalidadpago',
            options={'ordering': ('nombre',), 'verbose_name': 'modalidad de pago', 'verbose_name_plural': 'modalidades de pago'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'ordering': ('nombre',), 'verbose_name': 'moneda', 'verbose_name_plural': 'monedas'},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'ordering': ('nombre',), 'verbose_name': 'operador', 'verbose_name_plural': 'operadores'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nombre',), 'verbose_name': 'país', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('razon_social',), 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tipocuentabanco',
            options={'ordering': ('nombre',), 'verbose_name': 'tipo de cuenta banco', 'verbose_name_plural': 'tipos de cuenta banco'},
        ),
        migrations.AlterModelOptions(
            name='tipodocproveedor',
            options={'ordering': ('nombre',), 'verbose_name': 'tipo de documento proveedor', 'verbose_name_plural': 'tipos de documento proveedor'},
        ),
    ]
