# Generated by Django 2.0.5 on 2018-05-30 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180510_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacomercial',
            name='central_reservas',
            field=models.CharField(blank=True, help_text='Ingrese solo números', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{6,}$', message='Ingrese un número de teléfono fijo (central de reservas) válido.')], verbose_name='Central de reservas'),
        ),
    ]
