# Generated by Django 2.0.3 on 2018-03-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180327_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.CharField(help_text='Siglas del operador', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{2}$', message='Ingrese siglas válidas.'), django.core.validators.MinLengthValidator(2)], verbose_name='Siglas')),
                ('nombre', models.CharField(help_text='Nombre del operador', max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre')),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ('nombre',),
            },
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(help_text='Símbolo de la moneda', max_length=3, verbose_name='Símbolo'),
        ),
        migrations.AlterUniqueTogether(
            name='operador',
            unique_together={('nombre',)},
        ),
    ]
