# Generated by Django 2.0.5 on 2018-05-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marcacomercial_central_reservas'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE core_marcacomercial CHANGE COLUMN central_reservas central_reservas VARCHAR(12) NOT NULL AFTER telefono_movil;"),
    ]
