# Generated by Django 2.0.3 on 2018-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180327_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
    ]
