# Generated by Django 2.0.3 on 2018-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pais__estado_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='idioma',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='moneda',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='operador',
            name='_estado_obj',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1),
        ),
    ]
