# Generated by Django 2.0.3 on 2018-04-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180403_0916'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_pais CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER nombre"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_banco CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER nombre"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_ciudad CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER nombre"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_idioma CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER nombre"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_moneda CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER simbolo"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_operador CHANGE COLUMN _estado_obj _estado_obj VARCHAR(1) NOT NULL AFTER nombre"
        ),
    ]
