# Generated by Django 2.0.3 on 2018-04-05 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reordenar_columnas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Ingrese un número de documento válido.')], verbose_name='Número de documento')),
                ('razon_social', models.CharField(help_text='Nombre o razón social de la persona o empresa', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese una razón social válida.')], verbose_name='Razón social')),
                ('direccion', models.CharField(help_text='Dirección de la persona o empresa', max_length=170, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese una dirección válida.')], verbose_name='Dirección')),
                ('_estado_obj', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
                'verbose_name': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='TipoDocProveedor',
            fields=[
                ('id', models.CharField(help_text='Siglas del tipo de documento de proveedor', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3}$', message='Ingrese siglas válidas.')], verbose_name='Siglas')),
                ('nombre', models.CharField(help_text='Nombre del documento de proveedor', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre')),
                ('_estado_obj', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'tipos de documento proveedor',
                'verbose_name': 'tipo de documento proveedor',
            },
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pais'),
        ),
        migrations.AlterUniqueTogether(
            name='tipodocproveedor',
            unique_together={('nombre',)},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TipoDocProveedor', verbose_name='Tipo de documento'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('razon_social',)},
        ),
    ]
