# Generated by Django 2.0.3 on 2018-04-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reordenar_columnas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pais'),
        ),
    ]
