# Generated by Django 2.0.4 on 2018-04-17 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180416_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='id',
            field=models.CharField(help_text='Siglas de la moneda', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3}$', message='Ingrese siglas válidas.')], verbose_name='Siglas'),
        ),
    ]
