# Generated by Django 2.0.4 on 2018-04-18 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180417_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadPago',
            fields=[
                ('id', models.CharField(help_text='Siglas de la modalidad de pago', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3}$', message='Ingrese siglas válidas.')], verbose_name='Siglas')),
                ('nombre', models.CharField(help_text='Nombre de la modalidad de pago', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre')),
                ('_estado_obj', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
