# Generated by Django 2.0.4 on 2018-04-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_modalidadpago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidadpago',
            options={'verbose_name': 'modalidad de pago', 'verbose_name_plural': 'modalidades de pago'},
        ),
    ]
