# Generated by Django 2.0.4 on 2018-04-23 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tiposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la localidad', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese un nombre válido.')], verbose_name='Nombre')),
                ('altitud', models.PositiveIntegerField(default=0, help_text='Altitud de la localidad msnm', verbose_name='Altitud')),
                ('_estado_obj', models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Ciudad')),
            ],
        ),
    ]
