# Generated by Django 2.0.4 on 2018-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'localidad', 'verbose_name_plural': 'localidades'},
        ),
        migrations.AlterField(
            model_name='localidad',
            name='altitud',
            field=models.PositiveIntegerField(default=0, help_text='Altitud de la localidad m.s.n.m.', verbose_name='Altitud'),
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('nombre', 'ciudad')},
        ),
    ]
