# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(help_text='Nombre o razón social de la persona o empresa', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9áéíóúñÁÉÍÓÚÑ., \\-]+$', message='Ingrese una razón social válida.')], verbose_name='Razón social'),
        ),
    ]
