# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20171020_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='reservadetalle',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva'),
        ),
    ]
