# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20171020_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadetalle',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
